version: '3'

services:
  postgres:
    image: postgres:14.1-alpine
    env_file:
      - ./.docker-env
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api:
    depends_on:
      - postgres
      - start-minio
    restart: always
    image: golang:buster
    command: /api/scripts/wait-for-it/wait-for-it.sh postgres:5432 -t 120 -- /api/scripts/setup-postgres/setup-postgres-and-run-api.sh
    env_file:
      - ./.docker-env
    environment:
      - TEST=true
      - ENVIRONMENT=development
    volumes:
      - .:/api
    ports:
      - 7000:7000
    extra_hosts:
      - host.docker.internal:host-gateway

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"
    env_file:
      - ./.docker-env
    volumes:
      - minio-storage:/data
    ports:
      - 9000:9000
      - 9090:9090

  start-minio:
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - minio
    image: golang:buster
    command: /api/scripts/wait-for-it/wait-for-it.sh minio:9000 -t 120 -- /api/scripts/setup-minio.sh
    env_file:
      - ./.docker-env
    volumes:
      - .:/api

  e2etests:
    depends_on:
      - api
      - start-minio
    image: node:14-stretch
    command: /api/scripts/wait-for-it/wait-for-it.sh api:7000 -t 300 -- make -C /api e2etest-compose
    environment:
      API_HOST: "http://api:7000/"
    volumes:
      - .:/api

volumes:
  minio-storage: {}
