name: Backend Lint

on:
  pull_request:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/backend-lint.yaml

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses:
          actions/setup-go@v4
        with:
          go-version: 1.18
        id: go

      - name: Run lint
        run: make lint
        working-directory: ./backend
