name: Run end to end tests

on:
  pull_request:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/backend-e2etest.yaml

jobs:
  e2etest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.18
      - name: Run Backend Tests
        working-directory: ./backend
        run: make docker-e2etest
